###
POST http://localhost:8080/book/saveBook
Content-Type: application/json

{
  "isbn": "12345",
  "title": "bello12",
  "author": "alex",
  "date": "2020-12-07",
  "genre": "horror"
}

<> 2021-12-29T202005.200.json
<> 2021-12-29T201846.200.json
<> 2021-12-29T201813.200.json
<> 2021-12-29T201345.200.json

###
GET http://localhost:8080/book/getAllBooks

<> 2021-12-29T202009.200.json
<> 2021-12-29T201850.200.json
<> 2021-12-29T201841.200.json
<> 2021-12-29T201817.200.json
<> 2021-12-29T201806.200.json
<> 2021-12-29T201750.200.json
<> 2021-12-29T201722.200.json
<> 2021-12-29T200815.200.json

###
GET http://localhost:8080/book/getBookById?isbn=123456789

###
GET http://localhost:8080/book/getBooksByTitle?title=cccc

###
POST http://localhost:8080/book/updateBookTitle?title=cccc&isbn=123456789

###
POST http://localhost:8080/book/deleteBook?isbn=123456788

###
GET http://localhost:8080/book/getBooksByAuthor?author=alex

###
GET http://localhost:8080/bookCopy/getAllBookCopies

###
GET http://localhost:8080/bookCopy/getBookCopyById?id=2

###
GET http://localhost:8080/bookCopy/getBookCopiesByIsbn?isbn=123456788

###
POST http://localhost:8080/bookCopy/saveBookCopies?isbn=12345&numCopies=5
Content-Type: application/json

{
    "book":
    {
        "isbn": "123456789"
    }
}

###
POST http://localhost:8080/bookCopy/deleteBookCopy?id=3

###
GET http://localhost:8080/loan/getAllLoans

###
GET http://localhost:8080/loan/getLoansByUser?id=1

###
GET http://localhost:8080/loan/getBook?id=1

###
GET http://localhost:8080/loan/getLoansByBookCopy?id=1

###
POST http://localhost:8080/loan/saveLoan?user_id=1&bookCopy_id=2

###
POST http://localhost:8080/loan/closeLoan?id=1

###
GET http://localhost:8080/reservation/getAllReservations

###
GET http://localhost:8080/reservation/getUserByReservation?id=1

###
GET http://localhost:8080/reservation/getBookByReservation?id=1

###
GET http://localhost:8080/reservation/getReservationsByUser?id=1

###
POST http://localhost:8080/reservation/saveReservation?user_id=1&book_isbn=12345

###
POST http://localhost:8080/reservation/acceptReservation?id=1

###
POST http://localhost:8080/reservation/cancelReservation?id=1

###
GET http://localhost:8080/role/getAllRoles

###
POST http://localhost:8080/role/saveRole
Content-Type: application/json

{
    "id" : "2",
    "roleName" : "admin"
}

###
POST http://localhost:8080/role/updateRole?id=3&role=mamma

###
POST http://localhost:8080/role/deleteRole?id=3

###
GET http://localhost:8080/user/getAllUsers

<> 2021-12-29T202029.200.json

###
GET http://localhost:8080/user/getUserByMailAndPassword?mail=savio@&password=1234

###
GET http://localhost:8080/user/getUsersByRole?role=user

###
GET http://localhost:8080/user/getUserRole?id=1

###
POST http://localhost:8080/user/saveUser
Content-Type: application/json

{
    "name": "saviNREFFFGo",
    "surname": "marzana",
    "email": "savio@",
    "password": "1234",
    "cf": "mrzsvn",
    "address":{
        "city": "andria",
        "zipCode": "76123",
        "address": "via ada"
    }
}

<> 2021-12-29T202021.200.json

###
POST http://localhost:8080/user/updateUserAddress?id=1
Content-Type: application/json

{
  "city": "machu",
  "zip_code": "76123",
  "address": "via ada"
}

###
POST http://localhost:8080/user/updateUserRole?id=1&role=admin

###
POST http://localhost:8080/user/updateUserMail?id=1&mail=saviomarzano@gmail.com

###
POST http://localhost:8080/user/updateUserPassword?id=1&password=25071999q

###
POST http://localhost:8080/user/deleteUser?id=2

###
POST http://localhost:8080/book/updateBookTitle

###
GET http://localhost:8080/book/getBookById
